dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: UUID
    displayType: state
    state:
      label: '{{uuid.value}}'
automation:
  conditions: []
  actions: []
id: partyvoice23922.upnpuuid
version: 1
