dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: Name
    displayType: state
    state:
      label: '{{name.value}}'
automation:
  conditions: []
  actions: []
id: partyvoice23922.upnpname
version: 1
