dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: Device Status
    displayType: state
    state:
      label: '{{state.value}}'
automation:
  conditions: []
  actions: []
id: partyvoice23922.upnpstate
version: 1
