dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: IP Address
    displayType: state
    state:
      label: '{{addr.value}}'
automation:
  conditions: []
  actions: []
id: partyvoice23922.upnpaddr
version: 1
